# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_bc_perm_test <- function(x, y, h = 15L) {
    .Call(`_permtools_run_bc_perm_test`, x, y, h)
}

run_binom_mixture_perm_test <- function(x, y, alpha) {
    .Call(`_permtools_run_binom_mixture_perm_test`, x, y, alpha)
}

run_bc_multiple_test <- function(x, Y, h, alpha) {
    .Call(`_permtools_run_bc_multiple_test`, x, Y, h, alpha)
}

timesTwo <- function(x) {
    .Call(`_permtools_timesTwo`, x)
}

