# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_binom_mixture_perm_test <- function(x, y, alpha) {
    .Call(`_permtools_run_binom_mixture_perm_test`, x, y, alpha)
}

compute_binomial_right_tail_prob <- function(n, p, k) {
    .Call(`_permtools_compute_binomial_right_tail_prob`, n, p, k)
}

timesTwo <- function(x) {
    .Call(`_permtools_timesTwo`, x)
}

